### ISSUE TITLE
Suggest spring-boot-starter-elasticsearch-evolution support es with username/password security by default

### ISSUE THREAD

**Issue by yanfangli85** [senacor/elasticsearch-evolution#153]
It works good in my project，thanks ，It's a good tool.
but it doesn't work  when  elasticsearch add   username/password security ,  elasticsearch version is 6.8.6 ,    spring-boot-starter-elasticsearch-evolution 0.2.1.
I read doc 5.1.2.1 Custom RestClient help me. And I Suggest spring-boot-starter-elasticsearch-evolution support es with username/password security by default, It may be  a  usefully feature.
Enhance elasticsearchEvolutionAutoConfiguration  restHighLevelClient bean supprot username/password security 。

Hope to receive the good news from you！

**Comment by xtermi2** [comment]
Hi @yanfangli85 

Sorry, but we will not "fix" this, because
* ES 6.x is End of Live, see https://www.elastic.co/de/support/eol and hast major Security issues e.g. Log4Shell! You should switch to 8 ASAP!
* You can just define your own RestHighLevelClient Spring Bean and configure whatever you want, thats not part of Elasticsearch Evolution.

Best Regards
