### ISSUE TITLE
drop field

### ISSUE THREAD

**Issue by nilskuhn** [senacor/elasticsearch-evolution#16]
Hi,

I don't see a possibility to change a mapping in a way, that needs re-indexing of data, at the moment. If I would like to remove, for example, an existing field from an index, I could change the index name in my domain classes `@Document` annotation, having Spring create the new, empty index at startup. I could use evolution to re-index existing data from the old to the new index. This procedure would work for existing databases. But if somebody would start the same application with a fresh, empty elasticsearch cluster, the changeset would fail, because of the missing source index while trying to re-index old data. We would need a pre-condition for a changeset, where I could define something like "if index X exists" to enable this.

Does somebody have an idea / plan how to handle these kind of problems? 

I could just imagine the following approaches:
1. Don't change mapping. Use a changeset to remove field values from all docs in the index. I would end up with an index with a mapping, which does not match the domain classes definition :(
2. Doing the re-indexing outside of the application manually.

Both approaches don't make me happy ;)

Would be nice to hear, how others are handling these kind of issues.

**Comment by S1riU5** [comment]
I think at the moment, nothing in this direction is planned (correct me if that is wrong @xtermi2).  In my project we decided not to remove fields from the mapping. If needed, we would create a new field and migrate all the old data via an update by query script. If done long enough, you will end up with a lot of unused mapping fields. I think Checking if an index exists might be hard for the evolution library since this would require migration script content checking, if I understand you correctly. At the moment, we execute what's in the files. Not 100% sure if this helps, but maybe you can work with 2 different Evolution instances. 
Use one for the normal migration scripts and the second for reindexing operations. It's not the most straight forward approach but may do the trick. I can try to provide an example if I find some time, but this may take a while.

Cheers

**Comment by xtermi2** [comment]
In general, Elasticsearch-Evolution is not aware of how your Elasticsearch (indices, mappings, aliases, templates, ...) looks. 
It's in general a engine to execute HTTP requests against Elasticsearch and is not aware of what it executes, like [Flyway](https://flywaydb.org/) with SQL scripts for RDBMS. 
This behaviour will not change. When this is not sufficient you need another tool which is more like [Liquibase](https://www.liquibase.org/).

First you should think about if you really, really need to get rid of unused fields. 
If so, the best option is to use the pattern Elasticsearch suggests: Reindexing with aliases, something like [here](https://www.thirdrocktechkno.com/blog/6-steps-to-reindex-elasticsearch-data/). But this only works if your index is not too big, otherwise the reindex request can block the startup of your app very long.

Maybe a mixed approach is also a good compromise: Keep the mapping/index until you have reached too much unused fields and then do a manual reindexing. This could result in manual reindexing every couple of years, depending of how fast your app changes.

In my current company we don't use Elasticsearch-Evolution. We control the indices completely in the application and do reindexing if required combined with aliases. But our indices are not that big (~10 GB).

**Comment by nilskuhn** [comment]
Hi @S1riU5, hi @xtermi2,

thanks for your comments / explanations and good to know your plans for further development. Indeed, we are using evolution for elasticsearch mapping migrations like we would use liquibase for schema migrations in a relational database. It would feel more consistent, if it would be possible, to apply evolution changesets in an idempotent way. So, no matter, if I am running a fresh instance of my application or re-running from a previously started state / commit, I should end up with the same mappings in domain entities indices.

@xtermi2 Your proposal, to do a manual re-indexing, if domain classes and current indices diverge too much sounds reasonable on first glance. But than, I would have to remove old evolution changesets, too, whenever doing a re-indexing. For example, if these introduced (=added) new fields, that I was getting rid of now via re-indexing. So, each time I would do a re-indexing, I would have to rethink all the changeset history. Not really satisfactory.

For implementing a simple pre-check for a changeset, one could keep it very simple and just doing an es api call and check whether its response code is 2xx or not. That would be sufficient for my use case, doing a conditional re-indexing utilizing [index exist endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-exists.html).
